### ISSUE TITLE
add multiple pages and routes for Home Clubs Events

### ISSUE THREAD

**Issue by devxMani** [Yash-Ainapure/dypcetclubs.live#4]
Assign this task under GSOC Ext and Hacktoberfest labels

any insight you want to give ...............

**Comment by Yash-Ainapure** [comment]
> Assign this task under GSOC Ext and Hacktoberfest labels
> 
> any insight you want to give ...............

Could you explain what things you will do?
The thing I wanted is when we click on the navbar buttons(suppose events) then it should auto scroll to the events page present in bottom of out home page only and on the events of home page there should be a button (show more) on clicked on that ,it should redirect to the events page.

but before that #3  is still not done,so we cannot proceed with this at present until its done.
can you work on it? then will work on this issue further.

**Comment by devxMani** [comment]
@Yash-Ainapure  ok when it is done then I'll work on this feature till then I'll work on other features

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure ok when it is done then I'll work on this feature till then I'll work on other features

ok.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure ok when it is done then I'll work on this feature till then I'll work on other features

you can work on this now and the previous issue is solved now.

**Comment by devxMani** [comment]
@Yash-Ainapure ok bro any input you want to give you can

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure ok bro any input you want to give you can

It's same as given above.

**Comment by Yash-Ainapure** [comment]
> > Assign this task under GSOC Ext and Hacktoberfest labels
> > any insight you want to give ...............
> 
> Could you explain what things you will do? The thing I wanted is when we click on the navbar buttons(suppose events) then it should auto scroll to the events page present in bottom of out home page only and on the events of home page there should be a button (show more) on clicked on that ,it should redirect to the events page.
> 
> but before that #3 is still not done,so we cannot proceed with this at present until its done. can you work on it? then will work on this issue further.

.

**Comment by saloni911** [comment]
We appreciate your suggestion to auto-scroll to specific sections on the homepage when clicking navbar buttons (such as Events) and adding a "Show More" button to the Events section. However, before implementing this, there is an important prerequisite that still needs to be completed — specifically, issue #3.

Regarding the upcoming feature you mentioned, we recommend implementing proper routes for the Events page and other features instead of keeping everything on a single landing page. This will ensure better organization, improve load times, and enhance the overall user experience. By creating separate pages for different sections like Events, About, etc., users will navigate the site more easily and efficiently.

Once #3 is resolved, we can proceed with creating the auto-scroll functionality as well as routing for the additional Events page. This will allow us to ensure a cleaner, well-structured, and user-friendly website design. Let me know if you'd like us to proceed with #3 so we can move forward with this enhancement.

**Comment by Yash-Ainapure** [comment]
> We appreciate your suggestion to auto-scroll to specific sections on the homepage when clicking navbar buttons (such as Events) and adding a "Show More" button to the Events section. However, before implementing this, there is an important prerequisite that still needs to be completed — specifically, issue #3.
> 
> Regarding the upcoming feature you mentioned, we recommend implementing proper routes for the Events page and other features instead of keeping everything on a single landing page. This will ensure better organization, improve load times, and enhance the overall user experience. By creating separate pages for different sections like Events, About, etc., users will navigate the site more easily and efficiently.
> 
> Once #3 is resolved, we can proceed with creating the auto-scroll functionality as well as routing for the additional Events page. This will allow us to ensure a cleaner, well-structured, and user-friendly website design. Let me know if you'd like us to proceed with #3 so we can move forward with this enhancement.


1. #3 is solved now.
2. @devxMani  are you working on it??,else I'll assign to other person.
3. @saloni911 ,Iappreciate your thoughts about the issue,but the things is there must be some things present on the home/landing page so that the users would get a sight about the website( clubs,events,etc).
I was thinking about showing at max 4-5 clubs/events on home page with a explore more button for clubs and events to see all the other events&clubs which makes sense to show the top clubs/events on main page. As a user no one will directly navigate to clubs/events to see them before getting a sight about what it is about.

**Comment by devxMani** [comment]
@Yash-Ainapure i am working on it

**Comment by saloni911** [comment]
> > We appreciate your suggestion to auto-scroll to specific sections on the homepage when clicking navbar buttons (such as Events) and adding a "Show More" button to the Events section. However, before implementing this, there is an important prerequisite that still needs to be completed — specifically, issue #3.
> > Regarding the upcoming feature you mentioned, we recommend implementing proper routes for the Events page and other features instead of keeping everything on a single landing page. This will ensure better organization, improve load times, and enhance the overall user experience. By creating separate pages for different sections like Events, About, etc., users will navigate the site more easily and efficiently.
> > Once #3 is resolved, we can proceed with creating the auto-scroll functionality as well as routing for the additional Events page. This will allow us to ensure a cleaner, well-structured, and user-friendly website design. Let me know if you'd like us to proceed with #3 so we can move forward with this enhancement.
> 
> 1. [changing backend route urls to new routes. #3](https://github.com/Yash-Ainapure/dypcetclubs.live/issues/3) is solved now.
> 2. @devxMani  are you working on it??,else I'll assign to other person.
> 3. @saloni911 ,Iappreciate your thoughts about the issue,but the things is there must be some things present on the home/landing page so that the users would get a sight about the website( clubs,events,etc).
>    I was thinking about showing at max 4-5 clubs/events on home page with a explore more button for clubs and events to see all the other events&clubs which makes sense to show the top clubs/events on main page. As a user no one will directly navigate to clubs/events to see them before getting a sight about what it is about.

yes this seems to be a great idea, additional we can offer personalized suggestions based on user behavior (once they start interacting with the site). For example, "Recommended Clubs for You" or "Popular Events Near You" based on interests or geographic data And Trending section for events happening soon.
Search and Filter Options: Adding a prominent search bar and filter options for clubs and events will enhance user experience. Users should easily find the clubs or events they're interested in by type, date, or category.

**Comment by devxMani** [comment]
@saloni911  I am working on it give me some time because of college placements I don't have much time but I'll do it for sure...

**Comment by devxMani** [comment]
@saloni911 Yash didn't merged the previous PRs merge that it will be helpful

**Comment by saloni911** [comment]
@Yash-Ainapure Please assign this to me also, we can work together as a team.

**Comment by saloni911** [comment]
I had start the work for this issue.
